<a href="https://colab.research.google.com/github/slskdu/UNIV_2-2/blob/main/4%EC%A3%BC%EC%B0%A8_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_numpy_%EC%97%B0%EC%8A%B5_2026_up.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

아래 문제들은 결과 출력까시 실행 후 노트북 파일과 .py 파일을 제출


이름:전제형

1.1차원이면서 크기가 10이고 0으로 채워진 배열을 생성하고 다섯번째 요소를 1로 설정하는 코드를 작성하시오.

In [2]:
import numpy as np

x = np.array([0,0,0,0,0,0,0,0,0,0])
x[4] = 1
print(x)


[0 0 0 0 1 0 0 0 0 0]


2.아래와 같은 배열을 생성하는 code를 작성하시오.
arange 사용

[3,6,9,12,15,18,21]

In [5]:
import numpy as np
x = np.arange(3,22,3)
print(x)


[ 3  6  9 12 15 18 21]


3.0부터 8까지의 값을 가지고 크기가 3x3인 행렬을 arange와 reshape 명령어를 이용하여 생성 하시오.

[[0 1 2]    
 [3,4,5]  
 [6,7,8]]


In [10]:
import numpy as np
x = np.arange(0,9)
x.reshape(3,3)



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. arange, reshape을 이용하여 아래와 같은 배열 a를 만들고 print 하시오

[[0,1,2,3],  

 [4,5,6,7]]

In [12]:
import numpy as np
x = np.arange(0,8)
print(x.reshape(2,4))


[[0 1 2 3]
 [4 5 6 7]]


5. 위의 배열의 모든 값에 10을 더하고 print 하시오.

In [13]:
import numpy as np
x = np.arange(0,8)
y = x.reshape(2,4)
print(y+10)


[[10 11 12 13]
 [14 15 16 17]]


6. 다음 두 배열을 vstack으로 합치시오.   
A = np.array([1,2,3])   
B = np.array([4,5,6])   

In [14]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])

np.vstack((A,B))

array([[1, 2, 3],
       [4, 5, 6]])

7.난수로 채워진 3x3 배열을 생성하고 최대값과 최소값을 구하는 코드를 작성 하시오

In [20]:
import numpy as np
x = np.random.rand(3,3)

print(x)
t = (np.max(x))
m = (np.min(x))

print(t,m)

[[0.33941688 0.57641342 0.80140784]
 [0.36767452 0.69814775 0.71582564]
 [0.10695414 0.90601845 0.16614032]]
0.9060184477156639 0.10695413730400793


8. 다음 배열에서 두 번째 행만 출력하시오

[[1,2,3],    
 [4,5,6],    
 [7,8,9]]    

In [23]:
import numpy as np
x = np.arange(1,10)
x = x.reshape(3,3)

print(x[1,:])


[4 5 6]


9.다음과 같은 행렬을 만드는 code를 작성하시오.
(ones 함수와 slicing 이용)

[[1,1,1,0,0]    
  [1,1,1,0,0]  
  [1,1,1,0,0]   
  [1,1,1,1,1]]

In [27]:
import numpy as np
x = np.ones(20).reshape(4,5)
x[0:3,3:5] = 0
print(x)



[[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1.]]


10.5x5 행렬을 만들어 아래와 같은 패턴으로 채워보자 ( zeros 함수와 slicing 이용)

[[0,0,0,0,0]  
[1,1,1,1,1]  
[0,0,0,0,0]  
[1,1,1,1,1]  
[0,0,0,0,0]]  

In [33]:
import numpy as np
x = np.zeros(25).reshape(5,5)
x[1::2,:] = 1
print(x)


[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]


11.아래 a에서  
1) 10보다 값이 큰 원소의 인덱스 print  
2) 값이 0인 원소의 인덱스 print   


In [35]:
import numpy as np
a = np.array([3,6,2,0,5,8,15,3,0,6,0])
print(np.where(a>10))
print(np.where(a==0))



(array([6]),)
(array([ 3,  8, 10]),)


12.아래 code실행 후 a를 print했을때 아래와같이 나오도록 code를 추가 하시오.  
[ 9  8 10  9]

In [40]:
import numpy as np
a = np.array([9, 2, 3,4, 8, 7, 10, 9])
a = a[a >7]




print(b)의 결과가 다음과 같이 되는 code를 작성하시오..  
b는 a를 이용하여 정의 함.   

13
.   
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [47]:
import numpy as np
a=np.arange(16)

b= a[np.newaxis,:]

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


14.   
[  [ 0  1  2  3  4  5  6  7]  
   [ 8  9 10 11 12 13 14 15]  ]


In [66]:
import numpy as np
a=np.arange(16)
b= a[np.newaxis].reshape(2,8)


print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


15.

[ [ [ 0  1]  
    [ 2  3]  
    [ 4  5]  
    [ 6  7]  
    [ 8  9]  
    [10 11]  
    [12 13]  
    [14 15]]  ]  

In [68]:
import numpy as np
a=np.arange(16)
b = a.reshape(1, 8, 2)


print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


16.

[ [[ 0]  
   [ 1]  
   [ 2]]  

 [ [ 3]  
   [ 4]  
   [ 5] ]  

 [ [ 6]  
   [ 7]  
   [ 8]  ]  

 [ [ 9]  
   [10]  
   [11] ] ]  


In [73]:
import numpy as np
a=np.arange(12)
b = a.reshape(4, 3, 1)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0]
  [ 1]
  [ 2]]

 [[ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]]]


17. [8]  



In [76]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[1, 3:4]
print(b)

[8]
