<a href="https://colab.research.google.com/github/slskdu/UNIV_2-2/blob/main/numpy_assign_3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 배열 실습

이름 :

1. 다음 값을 가지는 NumPy 배열 a를 만드시오.

`10, 20, 30, 40, 50`

배열을 출력하시오.


In [4]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a)


[10 20 30 40 50]


2. 다음과 같은 2차원 NumPy 배열 a를 만드시오.

[[1, 2, 3], [4, 5, 6]]

배열을 출력하시오.


In [6]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


3. 다음 배열 a의 shape을 출력하시오.


In [7]:
import numpy as np

a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = a.shape
print(b)


(2, 3)


4. 다음 배열 a에 들어 있는 전체 원소의 개수를 출력하시오.


In [8]:
import numpy as np

a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

b = a.size
print(b)


8


5. 0으로 채워진 **3행 4열**의 배열을 만들고 출력하시오.


In [10]:
import numpy as np

a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


6. 1로 채워진 **4행 2열**의 배열을 만들고 출력하시오.


In [11]:
import numpy as np

a = np.ones((4,2))
print(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


7. 0부터 9까지의 정수를 가지는 배열을 `arange()`를 사용하여 만들고 출력하시오.


In [13]:
import numpy as np

a = np.arange(0,10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


8. 2부터 20까지의 **짝수**를 가지는 배열을 `arange()`를 사용하여 만들고 출력하시오.


In [15]:
import numpy as np

a = np.arange(2,21,2)
print(a)


[ 2  4  6  8 10 12 14 16 18 20]


9. 다음 두 배열 a, b를 하나의 1차원 배열로 연결하시오.

결과가 다음과 같이 나오도록 하시오.

[10 20 30 40 50 60]


In [35]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([40, 50, 60])

x = np.concatenate((a,b), axis=0)
print(x)



[10 20 30 40 50 60]


10. 다음 1차원 배열 a를 **2행 3열**의 2차원 배열로 변경하시오.

[1 2 3 4 5 6]


In [22]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

b = a.reshape(2,3)
print(b)


[[1 2 3]
 [4 5 6]]


11. 다음 배열 a를 `reshape()`와 `-1`을 사용하여 **3열을 가지는 2차원 배열**로 변경하시오.


In [23]:
import numpy as np

a = np.arange(1, 13)

b = a.reshape(-1,3)
print(b)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


12. 다음 1차원 배열 a의 shape은 `(4,)`이다.

newaxis를 사용하여 배열을 **4행 1열** 형태로 바꾸고, 변경된 배열과 shape을 출력하시오.


In [29]:
import numpy as np

a = np.array([10, 20, 30, 40])

b = a.reshape(4,1)
print(b)
print(b.shape)


[[10]
 [20]
 [30]
 [40]]
(4, 1)


13. 다음 1차원 배열 a를 newaxis를 사용하여 **1행 4열** 형태로 바꾸고, 변경된 배열과 shape을 출력하시오.


In [31]:
import numpy as np

a = np.array([10, 20, 30, 40])

b = a[np.newaxis,:]
print(b)
print(b.shape)


[[10 20 30 40]]
(1, 4)


14. 다음 배열 a가 주어져 있다.

a의 shape을 출력하시오.
a의 size를 출력하시오.
a를 **3행 4열**로 reshape하시오.
변경된 배열을 출력하시오.


In [33]:
import numpy as np

a = np.arange(1, 13)

print(a.shape,a.size)

b=a.reshape(3,4)
print(b)


(12,) 12
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
